#!/usr/bin/env python3
"""The inspection planner — a GOAL SOURCE, and nothing else. Strategy §5.2, §5.3, §3, §8.

ADR-004, invariant 12: this module answers "what next?". It holds no action client, opens no
action server, publishes no actuator command and starts no thread. The behaviour tree takes its
answers and streams them through the ONE existing `auv_depth_move_to` client — the same
mechanism `A_FarmInspection` uses, and the reason a second client or server on that name is
never built (SETTLED §1c: two servers stopped every mission at waypoint 1 for a week).

PURE PYTHON, no numpy: the whole point of this file is that a whole diversion can be walked
through in a test on a laptop, deterministically, including every refusal.

THE SEQUENCE (strategy §5.2, §5.3, §8)

    approach   one leg to a point ABEAM of the candidate on the way in — a free second SSS
               aspect before any camera frame exists, which is what promotes a candidate to
               `leader` (§7.1 rung 1)
    mode       command the sonar's INSPECTION mode and WAIT for the announcement
    ring       N stations on a circle of radius R around the candidate, at two altitudes,
               each facing the candidate, each followed by a capture burst
    mode       command NAVIGATION mode back
    surface    optional (`surface_between`), the default at Askö (D6)
    resume     a lead-in point on the interrupted leg's heading, then the diversion point P0
               itself — NOT the next waypoint. The remaining swath from P0 to its waypoint is
               otherwise a hole in the coverage nobody sees until Debrief (§8)
    done

EVERY REFUSAL NAMES ITS REASON (rule 12). The five the strategy lists are all checked at
`start`, before anything moves, and each returns the word an operator can act on.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

# Answer kinds. Mirrored as plain strings in `wasp_bt.bt.target_inspection_core` — DUPLICATED
# deliberately, exactly as `farm_inspection_core` duplicates the farm planner's, because wasp_bt
# must build on a hull with no perception package installed. The wire is the contract, and
# `wasp_bt/test/test_target_inspection_task.py` pins the two against each other.
GOAL = "goal"
PHASE_DONE = "phase_done"
MISSION_DONE = "mission_done"
REFUSED = "refused"
WAIT = "wait"
SONAR_MODE = "sonar_mode"
BURST = "burst"

#: Metres per degree. The same pair Mission Control uses; SETTLED §3u measured MC's metric math
#: at ~0.8 % off a geodesic, which over the ≤ 100 m distances a diversion covers is under 0.8 m
#: — inside the candidate's own sigma, and recorded here so nobody re-derives whether it matters.
M_PER_DEG_LAT = 110540.0
M_PER_DEG_LON_EQ = 111320.0


class PlannerRefusal(RuntimeError):
    """Raised only for programming errors (a malformed policy). Mission-level refusals are
    ANSWERS, not exceptions: a refusal the vehicle must report is a `REFUSED` answer with a
    reason and a response, exactly as the farm planner does."""


# --------------------------------------------------------------------------------------
# geometry
# --------------------------------------------------------------------------------------
def ne_offset(lat: float, lon: float, north_m: float, east_m: float) -> Tuple[float, float]:
    dlat = north_m / M_PER_DEG_LAT
    dlon = east_m / (M_PER_DEG_LON_EQ * max(math.cos(math.radians(lat)), 1e-6))
    return lat + dlat, lon + dlon


def ne_between(lat0: float, lon0: float, lat1: float, lon1: float) -> Tuple[float, float]:
    north = (lat1 - lat0) * M_PER_DEG_LAT
    east = (lon1 - lon0) * M_PER_DEG_LON_EQ * math.cos(math.radians(0.5 * (lat0 + lat1)))
    return north, east


def distance_m(lat0: float, lon0: float, lat1: float, lon1: float) -> float:
    n, e = ne_between(lat0, lon0, lat1, lon1)
    return math.hypot(n, e)


def bearing_deg(lat0: float, lon0: float, lat1: float, lon1: float) -> float:
    n, e = ne_between(lat0, lon0, lat1, lon1)
    return math.degrees(math.atan2(e, n)) % 360.0


# --------------------------------------------------------------------------------------
# inputs
# --------------------------------------------------------------------------------------
@dataclass(frozen=True)
class Policy:
    """The `adaptive` block, resolved. Defaults mirror `config/inspection_policy_defaults.yaml`,
    which is GENERATED by `scripts/adaptive-inspection/model_inspection_orbit.py` and carries
    each number's derivation. They are repeated here ONLY as a fallback for a mission that
    supplies a partial block; `from_dict` says which keys came from the mission."""

    ring_radius_m: float = 3.5
    ring_radius_floor_m: float = 3.468
    n_stations: int = 12
    altitudes_m: Tuple[float, ...] = (1.98, 2.98)
    ring_speed_ms: float = 0.3
    inspection_budget_s: float = 1200.0
    station_budget_s: float = 35.0
    max_divert_distance_m: float = 60.0
    max_diversions: int = 1
    surface_between: bool = True
    sonar_mode_close_ops: str = "inspection"
    sonar_mode_scan: str = "navigation"
    min_accepted_frames_per_station: int = 6
    lead_in_m: float = 10.0
    rpm: float = 500.0
    tolerance_m: float = 2.0
    #: Seconds to allow for getting back to P0 after the ring, on top of the inspection budget.
    #: Derived from the approach distance at the ring speed by `_return_estimate_s`, not stored.
    goal_timeout_s: float = 300.0

    @classmethod
    def from_dict(cls, d: Optional[dict]) -> "Policy":
        d = dict(d or {})
        alt = d.pop("altitudes_m", None)
        kwargs = {k: v for k, v in d.items() if k in cls.__dataclass_fields__}
        if alt is not None:
            kwargs["altitudes_m"] = tuple(float(a) for a in alt)
        p = cls(**kwargs)
        if p.ring_radius_m < p.ring_radius_floor_m:
            raise PlannerRefusal(
                f"ring_radius_m {p.ring_radius_m} is below the modelled floor "
                f"{p.ring_radius_floor_m} m (half-length + R_stop + sigma). Inside the floor the "
                f"protective stop fires and the inspection becomes a sequence of protective "
                f"stops. A number that disables a safety layer may not become a default "
                f"(invariant 8).")
        if p.n_stations < 3:
            raise PlannerRefusal(f"a ring of {p.n_stations} stations is not a ring")
        return p


@dataclass(frozen=True)
class DiversionPoint:
    """P0 — where the mission was interrupted, so it can be resumed there and not after it."""

    lat: float
    lon: float
    leg_id: int
    leg_fraction: float
    leg_heading_deg: float
    depth_m: float


@dataclass(frozen=True)
class TargetSite:
    """The candidate, and the seabed under it."""

    lat: float
    lon: float
    sigma_m: float
    seabed_depth_m: float
    id: str = "C1"


@dataclass(frozen=True)
class VehicleState:
    """What the planner is allowed to know about the vehicle. Four things, all measured."""

    lat: Optional[float]
    lon: Optional[float]
    estimator_age_s: float
    remaining_mission_s: Optional[float]
    diversions_used: int = 0


# --------------------------------------------------------------------------------------
# the plan
# --------------------------------------------------------------------------------------
@dataclass(frozen=True)
class Station:
    index: int
    ring: int
    lat: float
    lon: float
    depth_m: float
    heading_deg: float
    bearing_from_target_deg: float


def build_ring(site: TargetSite, policy: Policy) -> List[Station]:
    """N stations per altitude ring, each facing the candidate.

    Bearings are spread evenly and the SECOND ring is offset by half a step. That is not
    decoration: two rings at the same bearings give the bundle adjustment two views along the
    same line of sight and no extra convergence, while a half-step offset doubles the number of
    distinct bearings for free (§6.2 asks for convergent views from ≥ 10 bearings).
    """
    out: List[Station] = []
    step = 360.0 / policy.n_stations
    for r, alt in enumerate(policy.altitudes_m):
        for i in range(policy.n_stations):
            b = (i * step + (0.5 * step if r % 2 else 0.0)) % 360.0
            north = policy.ring_radius_m * math.cos(math.radians(b))
            east = policy.ring_radius_m * math.sin(math.radians(b))
            lat, lon = ne_offset(site.lat, site.lon, north, east)
            out.append(Station(index=len(out), ring=r, lat=lat, lon=lon,
                               depth_m=site.seabed_depth_m - alt,
                               heading_deg=(b + 180.0) % 360.0,
                               bearing_from_target_deg=b))
    return out


def approach_point(site: TargetSite, p0: DiversionPoint, policy: Policy) -> Tuple[float, float, float]:
    """A, on the ring at the bearing from the candidate BACK TOWARDS P0.

    Returns (lat, lon, abeam_offset_m). Approaching from the side the vehicle is already on is
    the shortest path and — more importantly — it flies PAST the candidate abeam on the way in,
    which is the free second SSS aspect §5.2 wants. `abeam_offset_m` is how far off the
    candidate that pass goes; it is reported so the caller can say whether the second look is
    inside the side scan's nadir gap (1.15·h) and therefore worthless.
    """
    b = bearing_deg(site.lat, site.lon, p0.lat, p0.lon)
    north = policy.ring_radius_m * math.cos(math.radians(b))
    east = policy.ring_radius_m * math.sin(math.radians(b))
    lat, lon = ne_offset(site.lat, site.lon, north, east)
    return lat, lon, policy.ring_radius_m


def _wp(lat: float, lon: float, depth: float, policy: Policy, name: str,
        heading_deg: Optional[float] = None, speed: Optional[float] = None) -> Dict[str, Any]:
    """A goal in the shape `ActionServerDiveSub.goal_callback` reads without a default.

    The five keys are checked by `farm_inspection_core._looks_like_a_waypoint` on the tree side
    too; a missing one raises inside the goal callback and rclpy turns that into a rejected goal
    with no explanation on the wire — a silent refusal, the hardest kind to diagnose
    (SETTLED §1b).
    """
    wp: Dict[str, Any] = {
        "latitude": float(lat), "longitude": float(lon), "target_depth": float(depth),
        "rpm": float(policy.rpm), "tolerance": float(policy.tolerance_m),
        "speed": float(policy.ring_speed_ms if speed is None else speed),
        "timeout": float(policy.goal_timeout_s),
    }
    if heading_deg is not None:
        wp["heading"] = float(heading_deg) % 360.0
    return {"waypoint": wp, "name": name, "timeout": float(policy.goal_timeout_s)}


# --------------------------------------------------------------------------------------
# the planner
# --------------------------------------------------------------------------------------
class InspectionPlanner:
    """One diversion, start to finish, as a sequence of answers.

    `what_next(event)` is the whole interface. `event` is the tree's request dict — the same
    `{"event": ..., "seq": n}` shape `FarmInspectionRunner._ask` sends — and the answer carries
    the same `seq` back, because a stale answer to a question we are no longer asking is how a
    plan skips a leg (`farm_inspection_core._answer`'s rule).
    """

    def __init__(self, policy: Policy, site: TargetSite, p0: DiversionPoint,
                 vehicle: VehicleState, *, now: float = 0.0,
                 duplicate_of: Optional[str] = None,
                 estimator_max_age_s: float = 5.0):
        self.policy = policy
        self.site = site
        self.p0 = p0
        self.vehicle = vehicle
        self.duplicate_of = duplicate_of
        self.estimator_max_age_s = float(estimator_max_age_s)
        self.started_at = float(now)
        self.stations = build_ring(site, policy)
        self.phase = "idle"
        self.refusal: Optional[Tuple[str, str, str]] = None
        self.finished = False
        self._steps: List[Dict[str, Any]] = []
        self._i = 0
        self.stations_reached = 0
        self.bursts_requested = 0
        self.consumed_s = 0.0

    # ---------------------------------------------------------------- refusals
    def _return_estimate_s(self) -> float:
        """Seconds to get from the ring back to P0 at the ring speed, plus the surfacing.

        Surfacing costs 1–2 min at this site (strategy §8) and the number used here is 120 s,
        the pessimistic end, because a budget check that is optimistic about the way home is a
        budget check that strands the mission.
        """
        d = distance_m(self.site.lat, self.site.lon, self.p0.lat, self.p0.lon)
        travel = d / max(self.policy.ring_speed_ms, 1e-3)
        return travel + (120.0 if self.policy.surface_between else 0.0)

    def refusal_reason(self) -> Optional[Tuple[str, str]]:
        """(reason, what to do about it) or None. Every branch names itself (rule 12).

        Checked in the order that costs least to establish, and each check is a different fact
        about why the plan may not proceed.
        """
        v = self.vehicle
        if v.lat is None or v.lon is None or v.estimator_age_s > self.estimator_max_age_s:
            return (f"the position estimate is {v.estimator_age_s:.1f} s old "
                    f"(limit {self.estimator_max_age_s:.1f} s)" if v.lat is not None else
                    "there is no position estimate at all",
                    "the diversion needs a live estimator to place a ring around the candidate "
                    "and to find its way back to the interrupted leg; the lawnmower continues "
                    "unchanged and the candidate is recorded as not_inspected")
        if self.duplicate_of is not None:
            return (f"this candidate is within its own sigma of {self.duplicate_of}, which has "
                    f"already been inspected",
                    "recorded as a re-observation of that target; no second diversion")
        if v.diversions_used >= self.policy.max_diversions:
            return (f"the mission's diversion budget is spent "
                    f"({v.diversions_used}/{self.policy.max_diversions})",
                    "the candidate is recorded with its position as not_inspected, which is "
                    "the input to a follow-up mission planned from the Debrief marker")
        d = distance_m(v.lat, v.lon, self.site.lat, self.site.lon)
        if d > self.policy.max_divert_distance_m:
            return (f"the candidate is {d:.0f} m away, beyond the "
                    f"{self.policy.max_divert_distance_m:.0f} m diversion limit",
                    "recorded as not_inspected with its position; raise "
                    "max_divert_distance_m in the mission's adaptive block if this site wants "
                    "longer diversions")
        need = self.policy.inspection_budget_s + self._return_estimate_s()
        if v.remaining_mission_s is not None and v.remaining_mission_s < need:
            return (f"the inspection needs {need:.0f} s (budget "
                    f"{self.policy.inspection_budget_s:.0f} s + "
                    f"{self._return_estimate_s():.0f} s to get back) and the mission has "
                    f"{v.remaining_mission_s:.0f} s left",
                    "recorded as not_inspected; the mission timeout is extended only by a "
                    "diversion that actually happened, so a diversion that cannot fit is "
                    "refused rather than started and abandoned")
        return None

    # ---------------------------------------------------------------- the plan
    def _build(self) -> None:
        p, s = self.policy, self.site
        alat, alon, abeam = approach_point(s, self.p0, p)
        steps: List[Dict[str, Any]] = []
        steps.append({"kind": GOAL, "phase": "approach",
                      "params": _wp(alat, alon, s.seabed_depth_m - p.altitudes_m[0], p,
                                    "approach_abeam"),
                      "reason": (f"approach the candidate from the side the vehicle is already "
                                 f"on, passing abeam at {abeam:.1f} m for a second side-scan "
                                 f"aspect before any camera frame exists")})
        steps.append({"kind": SONAR_MODE, "phase": "close_ops",
                      "mode": p.sonar_mode_close_ops,
                      "reason": (f"CLOSE-OPS entry: command the sonar's "
                                 f"{p.sonar_mode_close_ops} mode. The mission knows when it is "
                                 f"inspecting, the sonar does not (2026-08-12) — and the "
                                 f"protective stop reads the same cloud, so its horizon "
                                 f"changes with this command and must not change by itself")})
        for st in self.stations:
            steps.append({"kind": GOAL, "phase": "close_ops",
                          "params": _wp(st.lat, st.lon, st.depth_m, p,
                                        f"station_{st.index:02d}_r{st.ring}",
                                        heading_deg=st.heading_deg),
                          "station": st.index,
                          "reason": (f"station {st.index} of {len(self.stations)}, ring "
                                     f"{st.ring}, bearing {st.bearing_from_target_deg:.0f}° "
                                     f"from the candidate, facing it at "
                                     f"{st.heading_deg:.0f}°")})
            steps.append({"kind": BURST, "phase": "close_ops", "station": st.index,
                          "min_frames": p.min_accepted_frames_per_station,
                          "reason": (f"capture burst at station {st.index}; the station is "
                                     f"done when the recorder has ACCEPTED "
                                     f"{p.min_accepted_frames_per_station} frames, not when a "
                                     f"stopwatch says so")})
        steps.append({"kind": SONAR_MODE, "phase": "verify", "mode": p.sonar_mode_scan,
                      "reason": (f"CLOSE-OPS exit: revert the sonar to {p.sonar_mode_scan} so "
                                 f"the protective stop gets its full horizon back before the "
                                 f"vehicle moves at scan speed again")})
        if p.surface_between:
            steps.append({"kind": GOAL, "phase": "resume",
                          "params": _wp(s.lat, s.lon, 0.0, p, "surface_and_report",
                                        speed=p.ring_speed_ms),
                          "reason": ("surface, report and re-acquire a fix before resuming: "
                                     "fifteen minutes of near-zero speed is exactly where DR "
                                     "loses heading observability, and the candidate is a "
                                     "steel car")})
        lead_lat, lead_lon = ne_offset(
            self.p0.lat, self.p0.lon,
            -p.lead_in_m * math.cos(math.radians(self.p0.leg_heading_deg)),
            -p.lead_in_m * math.sin(math.radians(self.p0.leg_heading_deg)))
        steps.append({"kind": GOAL, "phase": "resume",
                      "params": _wp(lead_lat, lead_lon, self.p0.depth_m, p, "resume_lead_in",
                                    heading_deg=self.p0.leg_heading_deg),
                      "reason": (f"a {p.lead_in_m:.0f} m lead-in on the interrupted leg's own "
                                 f"heading ({self.p0.leg_heading_deg:.0f}°), so the side scan "
                                 f"re-enters the line straight instead of arriving across it")})
        steps.append({"kind": GOAL, "phase": "resume",
                      "params": _wp(self.p0.lat, self.p0.lon, self.p0.depth_m, p,
                                    "resume_at_diversion_point",
                                    heading_deg=self.p0.leg_heading_deg),
                      "resume": True, "leg_id": self.p0.leg_id,
                      "reason": (f"back to the diversion point on leg {self.p0.leg_id} at "
                                 f"{self.p0.leg_fraction:.0%} along it — NOT to the next "
                                 f"waypoint, or the swath from here to that waypoint is a hole "
                                 f"nobody sees until Debrief")})
        self._steps = steps

    # ---------------------------------------------------------------- the interface
    def what_next(self, event: Optional[dict] = None, *, now: Optional[float] = None) -> dict:
        """One answer. `event` is the tree's request; the answer echoes its `seq`."""
        ev = dict(event or {})
        seq = ev.get("seq")
        if now is not None:
            self.consumed_s = max(0.0, float(now) - self.started_at)
        ans = self._answer(ev)
        ans.setdefault("phase", self.phase)
        ans["seq"] = seq
        ans["consumed_s"] = round(self.consumed_s, 1)
        ans["budget_s"] = self.policy.inspection_budget_s
        ans["target_id"] = self.site.id
        return ans

    def _answer(self, ev: dict) -> dict:
        if self.refusal is not None:
            phase, reason, response = self.refusal
            return {"kind": REFUSED, "phase": phase, "reason": reason, "response": response}
        if self.finished:
            return {"kind": MISSION_DONE, "reason": "inspection complete"}

        kind = ev.get("event", "start")
        # THE REFUSAL CHECKS RUN BEFORE ANY PLAN EXISTS, whatever the event says. A tree that
        # asks "reached?" first — a re-tick after a subtree rebuild, say — must not walk past
        # the gate that decides whether this diversion may happen at all.
        if not self._steps:
            kind = "start"
        if kind == "start":
            r = self.refusal_reason()
            if r is not None:
                self.refusal = ("divert", r[0], r[1])
                self.phase = "divert"
                # ONE place produces a refusal answer, and it is the top of this method reading
                # `self.refusal`. Returning a freshly-built dict here as well would mean the
                # first tick's refusal and every later tick's refusal came from two different
                # lines, and a test that only drove one of them would pass over a defect in the
                # other. Re-entering is cheap and keeps the shape single.
                return self._answer({"event": "poll"})
            if not self._steps:
                self._build()
                self.phase = "approach"
        elif kind == "reached":
            self._i += 1
        elif kind == "next":
            self._i += 1
        elif kind == "poll":
            pass

        # The budget is checked BETWEEN steps, never in the middle of one: a diversion that runs
        # out of time mid-station is a planned end (verdict `inconclusive`, strategy §3), not an
        # emergency, and it must still fly the resume legs.
        if self.consumed_s > self.policy.inspection_budget_s and self._i < len(self._steps):
            first_resume = next((j for j, s in enumerate(self._steps)
                                 if s["phase"] == "resume"), len(self._steps))
            if self._i < first_resume:
                self.phase = "verify"
                self._i = first_resume
                return {"kind": PHASE_DONE, "phase": "verify",
                        "reason": (f"the inspection budget of "
                                   f"{self.policy.inspection_budget_s:.0f} s is spent after "
                                   f"{self.stations_reached} of {len(self.stations)} stations; "
                                   f"this is a planned end, not an emergency — the verdict is "
                                   f"`inconclusive` and the vehicle resumes its plan"),
                        "verdict_hint": "inconclusive"}

        if self._i >= len(self._steps):
            self.finished = True
            self.phase = "done"
            return {"kind": MISSION_DONE,
                    "reason": (f"inspection complete: {self.stations_reached} of "
                               f"{len(self.stations)} stations reached, "
                               f"{self.bursts_requested} capture bursts requested, "
                               f"{self.consumed_s:.0f} s consumed")}

        step = self._steps[self._i]
        self.phase = step["phase"]
        if step["kind"] == GOAL:
            if "station" in step:
                # +1: `station` is a zero-based index and `stations_reached` is a COUNT. Off by
                # one here would report 11 of 12 stations on a complete ring, which is exactly
                # the coverage number the verdict ladder's rung 2 thresholds on.
                self.stations_reached = max(self.stations_reached, int(step["station"]) + 1)
            out = {"kind": GOAL, "phase": step["phase"], "params": step["params"],
                   "reason": step["reason"]}
            for k in ("station", "resume", "leg_id"):
                if k in step:
                    out[k] = step[k]
            return out
        if step["kind"] == SONAR_MODE:
            return {"kind": SONAR_MODE, "phase": step["phase"], "mode": step["mode"],
                    "reason": step["reason"]}
        if step["kind"] == BURST:
            self.bursts_requested += 1
            return {"kind": BURST, "phase": step["phase"], "station": step["station"],
                    "min_frames": step["min_frames"], "reason": step["reason"]}
        raise PlannerRefusal(f"a step of kind {step['kind']!r} was built and cannot be answered")

    # ---------------------------------------------------------------- reporting
    def budget_report(self) -> dict:
        """What the mission timeout must be extended by (strategy §3, SETTLED §3p's rule).

        A good inspection may never be how a good mission dies, so the extension is the time the
        SANCTIONED diversion actually consumed — measured, not the budget it was allowed.
        """
        return {"consumed_s": round(self.consumed_s, 1),
                "budget_s": self.policy.inspection_budget_s,
                "stations_reached": self.stations_reached,
                "stations_planned": len(self.stations),
                "bursts": self.bursts_requested,
                "extend_mission_timeout_by_s": round(self.consumed_s, 1)}
